- hosts: b1,b2,b3,b4,b5
  become: true
  tasks:

    - name: Remove all files in /home/mhemmings/wrk-output/
      shell: rm -r /home/mhemmings/wrk-output/*
  
    - name: Stop all running containers if any are present
      shell: docker ps -q
      register: running_containers
      changed_when: false

    - name: stop docker containers
      shell: bash -c "docker-compose -f /tmp/docker-compose-4-containers/docker-compose.yaml --project-directory /tmp/docker-compose-4-containers down -v"
      register: docker_build

    - name: Stop running containers
      shell: docker stop $(docker ps -q)
      when: running_containers.stdout | length > 0

    - name: Remove all stopped containers
      shell: docker container prune -f
      register: container_prune_output
      changed_when: "'Total reclaimed space' in container_prune_output.stdout"

    #- name: Remove all Docker images
    #  shell: docker image prune -a -f
    #  register: image_prune_output
    #  changed_when: "'Total reclaimed space' in image_prune_output.stdout"

    - name: Remove all unused volumes
      shell: docker volume prune -f
      register: volume_prune_output
      changed_when: "'Total reclaimed space' in volume_prune_output.stdout"

    - name: Remove all unused networks
      shell: docker network prune -f
      register: network_prune_output
      changed_when: "'Total reclaimed space' in network_prune_output.stdout"

    
