- hosts: b1,b2,b3,b4,b5,b6,b7,b8,b9,b10
  strategy: free
  become: true
  tasks:
    - name: Copy install docker script
      copy:
        src: /project/mhemmings/notebooks/get-docker.sh
        dest: /tmp/get-docker.sh        

    - name: Run install docker script
      shell: bash /tmp/get-docker.sh 2>&1 | awk '{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0 }'
      register: docker_install

    - name: Copy entire folder from host to remote node
      copy:
        src: /project/mhemmings/notebooks/nyu-testing/docker-compose-4-containers
        dest: /tmp/
        
    - name: Install libraries
      shell: bash /tmp/docker-compose-4-containers/install_libraries.sh

    - name: Create output directory if it does not exist
      file:
        path: /home/mhemmings/wrk-output
        state: directory
    
    - name: Set ownership of /home/mhemmings/wrk-output
      file:
        path: /home/mhemmings/wrk-output
        owner: 1000
        group: 1000
    
    - name: Set permissions of /home/mhemmings/wrk-output to 755
      file:
        path: /home/mhemmings/wrk-output
        mode: '0755'
   

    - name: Build and start docker containers
      shell: bash -c "docker-compose -f /tmp/docker-compose-4-containers/docker-compose.yaml --project-directory /tmp/docker-compose-4-containers up -d"
      register: docker_build

    - name: Write docker build output to local file
      copy:
        content: "{{ docker_build.stdout }}\n{{ docker_build.stderr }}"
        dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_{{ ansible_date_time.iso8601_basic }}_build.log"      

    - name: Wait for 2.5 minutes
      shell: sleep 150
      async: 0
      poll: 0

    - name: Run wrk job inside lind plaintext container
      command: >        
        docker-compose exec lind_lamp_plaintext
        bash -c "cd /home/lind/lind_project && ./wrk_plaintext"
      args:
        chdir: /tmp/docker-compose-4-containers
      register: wrk_plaintext

    - name: Run wrk job inside lind plaintext container
      command: >
        docker-compose exec lind_lamp_plaintext
        bash -c "cd /home/lind/lind_project && ./wrk_plaintext"
      args:
        chdir: /tmp/docker-compose-4-containers
      register: wrk_plaintext


    - name: Run wrk job inside lind queries container
      command: >        
        docker-compose exec lind_lamp_plaintext
        bash -c "cd /home/lind/lind_project && ./wrk_queries"
      args:
        chdir: /tmp/docker-compose-4-containers
      register: wrk_queries

    - name: Run wrk job inside lind mixed container
      command: >        
        docker-compose exec lind_lamp_plaintext
        bash -c "cd /home/lind/lind_project && ./wrk_mixed"
      args:
        chdir: /tmp/docker-compose-4-containers
      register: wrk_mixed

    - name: Run wrk job inside lind nginx container
      command: >
        cd /tmp/docker-compose-4-containers &&
        docker-compose exec lind_lamp_plaintext
        bash -c "cd /home/lind/lind_project && ./wrk_nginx"
      register: wrk_nginx

    - name: Write output for wrk plaintext job
      copy:
        content: "{{ wrk_plaintext.stdout }}\n{{ wrk_plaintext.stderr }}"
        dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_plaintext_wrk.log"

    - name: Write output for wrk mixed job
      copy:
        content: "{{ wrk_mixed.stdout }}\n{{ wrk_mixed.stderr }}"
        dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_mixed_wrk.log"

    - name: Write output for wrk queries job
      copy:
        content: "{{ wrk_queries.stdout }}\n{{ wrk_queries.stderr }}"
        dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_queries_wrk.log"
    
    - name: Write output for wrk nginx job
      copy:
        content: "{{ wrk_nginx.stdout }}\n{{ wrk_nginx.stderr }}"
        dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_nginx_wrk.log"    
    
    - name: Create tar.gz archive of wrk output files
      archive:
        path: "/home/mhemmings/wrk-output/*"
        dest: "/tmp/wrk_output_{{ ansible_hostname }}.tar.gz"
        format: gz
    
    - name: Collect tarballs and organize by type of test
      fetch:
        src: "/tmp/wrk_output_{{ ansible_hostname }}.tar.gz"
        dest: "/project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ 'docker-compose-4-containers' }}--{{ ansible_hostname }}"
      
    - name: Untar the collected tarball on the host machine
      command: >
        tar -xzf /project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ 'docker-compose-4-containers' }}--{{ ansible_hostname }}/{{ ansible_hostname }}/tmp/wrk_output_{{ ansible_hostname }}.tar.gz -C /project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ 'docker-compose-4-containers' }}--{{ ansible_hostname }}
      delegate_to: localhost

    - name: Bring down docker containers
      shell: bash -c "docker-compose -f /tmp/docker-compose-4-containers/docker-compose.yaml --project-directory /tmp/docker-compose-4-containers down -v"

    #- name: Stop running containers
    #  shell: docker stop $(docker ps -aq)

    #- name: Delete containers
    #  shell: bash -c "docker rm $(docker ps -aq)"
