services:
  lind_lamp_plaintext:
    build:
      context: .
      dockerfile: lind_lamp_plaintext/Dockerfile
    container_name: lind_lamp_plaintext
    command: >
      bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling &&
               ./run_lamp_native.sh"
    ports:
      - "8081:80"
    networks:
      - lind_network
    volumes:
      - /home/mhemmings/wrk-output:/home/lind/lind_project/data


  lind_lamp_queries:
    build:
      context: .
      dockerfile: lind_lamp_queries/Dockerfile
    container_name: lind_lamp_queries
    ports:
      - "8082:80"
    networks:
      - lind_network
    volumes:
      - /home/mhemmings/wrk-output:/home/lind/lind_project/data


  lind_lamp_mixed:
    build:
      context: .
      dockerfile: lind_lamp_mixed/Dockerfile
    container_name: lind_lamp_mixed
    ports:
      - "8083:80"
    networks:
      - lind_network
    volumes:
      - /home/mhemmings/wrk-output:/home/lind/lind_project/data


  lind_lamp_nginx:
    build:
      context: .
      dockerfile: lind_lamp_nginx/Dockerfile
    container_name: lind_lamp_nginx
    ports:
      - "8084:80"
    networks:
      - lind_network
    volumes:
      - /home/mhemmings/wrk-output:/home/lind/lind_project/data  

networks:
  lind_network:
    driver: bridge
