- hosts: b1
  strategy: free
  become: true
  tasks:
    - name: Run full workflow in a loop
      block:
        - name: Generate unique timestamp for this iteration
          command: date +%Y%m%d%H%M%S
          register: unique_timestamp
          delegate_to: localhost
          
        - name: Remove all contents from /home/mhemmings/wrk-output
          shell: rm -rf /home/mhemmings/wrk-output/*
          args:
            warn: false

        - name: Build and start docker containers
          shell: bash -c "docker-compose -f /tmp/docker-compose-4-containers/docker-compose.yaml --project-directory /tmp/docker-compose-4-containers up -d --build"
          register: docker_build

        - name: Write docker build output to local file
          copy:
            content: "{{ docker_build.stdout }}\n{{ docker_build.stderr }}"
            dest: "/home/mhemmings/wrk-output/{{ ansible_hostname }}_{{ unique_timestamp.stdout }}_build.log"

        - name: Wait for 2.5 minutes
          shell: sleep 150
          async: 0
          poll: 0

        - name: Run wrk job inside lind mixed container
          command: >        
            docker exec lind_lamp_mixed
            bash -c "cd /home/lind/lind_project && ./wrk_mixed.sh 1 300 lind"
          args:
            chdir: /tmp/docker-compose-4-containers
          register: wrk_mixed

        - name: Create tar.gz archive of wrk output files
          archive:
            path: "/home/mhemmings/wrk-output/*"
            dest: "/tmp/wrk_output_{{ ansible_hostname }}_{{ unique_timestamp.stdout }}.tar.gz"
            format: gz

        - name: Collect tarballs and organize by type of test
          fetch:
            src: "/tmp/wrk_output_{{ ansible_hostname }}_{{ unique_timestamp.stdout }}.tar.gz"
            dest: "/project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ unique_timestamp.stdout }}--docker-compose-4-containers-300-seconds--{{ ansible_hostname }}"

        - name: Untar the collected tarball on the host machine
          command: >
            tar -xzf /project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ unique_timestamp.stdout }}--docker-compose-4-containers-300-seconds--{{ ansible_hostname }}/{{ ansible_hostname }}/tmp/wrk_output_{{ ansible_hostname }}_{{ unique_timestamp.stdout }}.tar.gz -C /project/mhemmings/notebooks/lind-ipc-data/sphere-data/{{ unique_timestamp.stdout }}--docker-compose-4-containers-300-seconds--{{ ansible_hostname }}
          delegate_to: localhost

        - name: Bring down docker containers
          shell: bash -c "docker-compose -f /tmp/docker-compose-4-containers/docker-compose.yaml --project-directory /tmp/docker-compose-4-containers down -v"

        - name: Pause for 30 seconds before the next iteration
          pause:
            seconds: 30

      loop: "{{ range(1, 4) | list }}"  # Adjust the range to set the number of iterations
      loop_control:
        label: "Full workflow iteration {{ item }}"
