services:
  lind_lamp_mixed:
    image: securesystemslab/lind_ubuntu:lind-pgbench-docker
    container_name: lind-pgbench
    user: root
    privileged: true
    ipc: host
    cap_add:
      - SYS_PTRACE
    ports:
      - "8083:80"
    command: >
      "cd /tmp/lind_project && source general.sh && ./grab_lind_pg.sh 5 2>&1 | tee /tmp/data/run.log && cp /tmp/lind_project/tps_data.json /tmp/data"      
    networks:
      - lind_network
    volumes: #Verify that this folder is empty, else the test may need adjusting
      - /home/mhemmings/output:/tmp/data

networks:
  lind_network:
    driver: bridge