services:
  #native_lamp_plaintext:
  #    image: securesystemslab/lind_ubuntu:native_lamp_plaintext2
  #    container_name: native_lamp_plaintext
  #    user: lind
  #    privileged: true
  #    ipc: host
  #    cap_add:
  #      - SYS_PTRACE
  #    ports:
  #      - "8081:80"
  #    command: >
  #      /bin/bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling/ \
  #      && ./nat_run_lamp.sh"
  #    networks:
  #      - lind_network
  #    volumes:
  #      - /home/mhemmings/wrk-output:/home/lind/lind_project/data

  #native_lamp_queries:
  #  image: securesystemslab/lind_ubuntu:native_lamp_queries2
  #  container_name: native_lamp_queries
  #  user: lind
  #  privileged: true
  #  ipc: host
  #  cap_add:
  #    - SYS_PTRACE
  #  ports:
  #    - "8082:80"
  #  command: >
  #    /bin/bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling/ \
  #    && ./nat_run_lamp.sh"
  #  networks:
  #    - lind_network
  #  volumes:
  #    - /home/mhemmings/wrk-output:/home/lind/lind_project/data

  native_lamp_mixed:
      image: securesystemslab/lind_ubuntu:native_lamp_mixed2
      container_name: native_lamp_mixed
      user: lind
      privileged: true
      ipc: host
      cap_add:
        - SYS_PTRACE
      ports:
        - "8083:80"
      command: >
        /bin/bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling/ \
        && ./nat_run_lamp.sh"
      networks:
        - lind_network
      volumes:
        - /home/mhemmings/wrk-output:/home/lind/lind_project/data

  #native_lamp_nginx:
  #    image: securesystemslab/lind_ubuntu:native_nginx_static
  #    container_name: native_lamp_nginx
  #    user: lind
  #    privileged: true
  #    ipc: host
  #    cap_add:
  #      - SYS_PTRACE
  #    ports:
  #      - "8084:80"
  #    command: >
  #      /bin/bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling/ \
  #      && ./nat_run_nginx.sh && tail -f /dev/null"
  #    networks:
  #      - lind_network
  #    volumes:
  #      - /home/mhemmings/wrk-output:/home/lind/lind_project/data

networks:
  lind_network:
    driver: bridge
