- name: Upgrade Debian 11 to Debian 12 (Non-interactive)
  hosts: all
  become: yes
  strategy: free
  vars:
    apt_env: 
      DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      environment: "{{ apt_env }}"

    - name: Upgrade all installed packages
      apt:
        upgrade: dist
      environment: "{{ apt_env }}"

    - name: Perform full upgrade
      apt:
        upgrade: full
      environment: "{{ apt_env }}"

    - name: Update sources list from bullseye to bookworm
      lineinfile:
        path: /etc/apt/sources.list
        regexp: 'bullseye'
        line: "{{ item }}"
      loop:
        - 'deb http://deb.debian.org/debian/ bookworm main contrib non-free'
        - 'deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free'
        - 'deb http://security.debian.org/debian-security bookworm-security main contrib non-free'

    - name: Update package list after sources update
      apt:
        update_cache: yes
      environment: "{{ apt_env }}"

    - name: Minimal upgrade
      apt:
        upgrade: safe
      environment: "{{ apt_env }}"

    - name: Full upgrade
      apt:
        upgrade: full
      environment: "{{ apt_env }}"

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
      environment: "{{ apt_env }}"

    - name: Reboot the system
      reboot:
        msg: "Rebooting after upgrade"
        connect_timeout: 5
        reboot_timeout: 600
