#version: '3'
services:
  #wrk:
  #  build: ./wrk
  #  container_name: wrk
  #  depends_on:
  #    - lind_benchmark
  #  networks:
  #    - benchmark-network

  lind_benchmark:
    image: securesystemslab/lind_ubuntu:native_lamp
    container_name: lind_benchmark_container
    user: lind
    privileged: true
    ipc: host
    cap_add:
      - SYS_PTRACE
    ports:
      - "80:80"
    command: >
      bash -c "cd /home/lind/lind_project/tests/lamp_stack/profiling &&
               ./run_lamp_native.sh"
  
    networks:
      - benchmark-network
    volumes:
      - /home/mhemmings/wrk-output:/home/lind/lind_project/data
networks:
  benchmark-network:
    driver: bridge
