- hosts: a1
  strategy: free
  become: true
  vars_files:
    - buffer_allocation_vars.yaml
    - ipc_total_runtime_vars.yaml
    - sfi_penalty_vars.yaml
    - syscall_overhead_vars.yaml

  tasks:
    - name: Install libraries on remote node using libraries.sh
      script: libraries.sh
      
    - name: Remove all contents of /tmp/lind_project but keep the directory
      shell: |        
          rm -rf /tmp/*        
          if [ ! -d /tmp ]; then
            mkdir -p /tmp
          fi
        
    - name: Ensure /tmp/data directory exists
      file:
        path: /tmp/data
        state: directory
        mode: '0755'        
    
    - name: Copy file from local machine
      copy:
        src: "/home/mhemmings/hello/lind_total_runtime.tar.gz"
        dest: "/tmp/lind_total_runtime.tar.gz"
      register: copy_output

    - name: Untar the file
      unarchive:
        src: "/tmp/lind_total_runtime.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Copy test script to remote node
      copy:
        src: "{{ test_file_location_localhost }}"
        dest: /tmp/lind_project/test_script.sh
        mode: '0755'

    - name: Execute the test script on the remote node and log output
      shell: "bash -c '{{ execute_script_command }}' 2>&1 | tee /tmp/run.log"
      register: script_output
    - name: Move /tmp/run.log to /tmp/lind_project/data/run.log
      shell: mv /tmp/run.log /tmp/lind_project/data/run.log      
      register: move_log_output
      
    #- debug: msg="{{ script_output.stdout }}"
    #- debug: msg="{{ script_output.stderr }}"

    - name: Create a tar.gz archive of the /tmp/lind_project/data directory
      archive:
        path: "{{ output_file_location }}"
        dest: /tmp/lind_project/data.tar.gz
        format: gz
    
    - name: collect tarballs
      fetch:
        src: /tmp/lind_project/data.tar.gz
        dest: ~/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data
        flat: no
    #- name: Debug tarball path
    #  debug:
    #    msg: "Tarball path: ~/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data/{{ ansible_hostname }}/tmp/lind_project/data.tar.gz"
    
    #- name: Debug extraction directory
    #  debug:
    #    msg: "Extraction directory: ~/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data/"

    - name: Untar the collected tarball on the host machine
      command: tar -xzf /home/mhemmings/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data/{{ ansible_hostname }}/tmp/lind_project/data.tar.gz -C /home/mhemmings/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data/
      delegate_to: localhost
    - name: Remove the specific results folder
      file:
        path: /home/mhemmings/lind-ipc-data/sphere-data/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}--{{ ansible_hostname }}--data/{{ ansible_hostname }}
        state: absent
      delegate_to: localhost