- name: Upgrade Debian 11 to Debian 12 (Non-interactive)
  hosts: a6,a7,a8,a9,a10
  become: yes
  strategy: free
  gather_facts: yes
  vars:
    apt_env:
      DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Get the current hostname
      set_fact:
        current_hostname: "{{ ansible_hostname }}"

    - name: Backup the current /etc/resolv.conf
      copy:
        dest: /tmp/resolv.conf.backup
        src: /etc/resolv.conf
        remote_src: yes

    - name: Ensure /etc/hosts has correct hostname entry
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: "127.0.1.1   {{ current_hostname }}"
        backup: yes

    - name: Set the hostname (if changed)
      hostname:
        name: "{{ current_hostname }}"

    - name: Debug DNS information
      debug:
        var: ansible_dns

    - name: Ensure /etc/resolv.conf has correct DNS servers
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        owner: root
        group: root
        mode: '0644'
        backup: yes


    - name: Restart systemd-resolved if available
      service:
        name: systemd-resolved
        state: restarted
      when: ansible_facts.services['systemd-resolved'] is defined

    - name: Restart networking if available
      service:
        name: networking
        state: restarted
      when: ansible_facts.services['networking'] is defined

    - name: Restart NetworkManager if available
      service:
        name: NetworkManager
        state: restarted
      when: ansible_facts.services['NetworkManager'] is defined

    - name: Update package list
      apt:
        update_cache: yes
      environment: "{{ apt_env }}"

    - name: Upgrade all installed packages
      apt:
        upgrade: dist
      environment: "{{ apt_env }}"

    - name: Perform full upgrade
      apt:
        upgrade: full
      environment: "{{ apt_env }}"

    - name: Update sources list from bullseye to bookworm
      lineinfile:
        path: /etc/apt/sources.list
        regexp: 'bullseye'
        line: "{{ item }}"
      loop:
        - 'deb http://deb.debian.org/debian/ bookworm main contrib non-free'
        - 'deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free'
        - 'deb http://security.debian.org/debian-security bookworm-security main contrib non-free'

    - name: Update package list after sources update
      apt:
        update_cache: yes
      environment: "{{ apt_env }}"

    - name: Minimal upgrade
      apt:
        upgrade: safe
      environment: "{{ apt_env }}"

    - name: Full upgrade
      apt:
        upgrade: full
      environment: "{{ apt_env }}"

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
      environment: "{{ apt_env }}"

    - name: Restore the original nameserver
      copy:
        dest: /etc/resolv.conf
        src: /tmp/resolv.conf.backup
        remote_src: yes

    - name: Check if NetworkManager is running
      shell: systemctl is-active NetworkManager
      register: nm_status
      ignore_errors: yes

    - name: Configure NetworkManager DNS servers for non-loopback interfaces
      nmcli:
        conn_name: '{{ item }}'
        dns4: '8.8.8.8 8.8.4.4'
        state: present  # Ensure the connection is present
      loop: "{{ ansible_interfaces }}"
      when: item != 'lo' and nm_status.stdout == 'active'

    - name: Restart NetworkManager service
      service:
        name: NetworkManager
        state: restarted
      when: nm_status.stdout == 'active'

    - name: Reboot the system
      reboot:
        msg: "Rebooting after upgrade"
        connect_timeout: 5
        reboot_timeout: 600
