version: '3.8'

services:
  postgres:
    build: 
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - benchmark_network
    ports:  
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-benchmark:
    build: 
      context: ./flask-benchmark
    environment:
      DATABASE: postgres_test_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - benchmark_network

networks:
  benchmark_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
